import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <header style={{
          backgroundColor: '#ffd29e',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '12px',
        }}>
          
        <span style={{ color: '#ffffff', fontWeight: 'bold', fontSize: '24px' }}>
          <Link href="/">ArtPort</Link>     {/* logo that acts as a route to home page */}
        </span>

        <nav style={{ display: 'flex', gap: '16px' }}>
          <Link href="/user_profile" style={{ color: 'white', textDecoration: 'none' }}>Profile</Link>
        </nav>
        </header>

        {children}                    {/*indivual pages start here*/}
      
      </body>
    </html>
  );
}
